http/frameworks/rails-example/config/routes.rb
RailsExample::Application.routes.draw do
  resources :shoes
end

http/frameworks/rails-example/app/models/shoe.rb
class Shoe < ActiveRecord::Base
  validates :name, :presence => true
  validates :size, :presence => true
  validates :color, :presence => true
  validates :description, :presence => true
end

http/frameworks/rails-example/app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  # GET /shoes
  def index 
    @shoes = Shoe.all
  end

  # GET /shoes/X
  def show
    @shoe = Shoe.find(params[:id])
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # POST /shoes
  def create
    @shoe = Shoe.new(params[:shoe])
    if @shoe.save
      redirect_to shoes_path
    else
      render :action => "new"
    end
  end

  # GET /shoes/X
  def edit
    @shoe = Shoe.find(params[:id])
  end

  # PUT /shoes/X
  def update
    @shoe = Shoe.find(params[:id])
    if @shoe.update_attributes(params[:shoe])
      redirect_to shoes_path
    else
      render :action => "edit"
    end
  end

  # DELETE /shoes/X
  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy
    redirect_to shoes_path
  end
end

http/frameworks/rails-example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

http/frameworks/rails-example/app/views/shoes/_form.erb
<%= form_for @shoe do |f| %>
  <% if @shoe.errors.any? -%>
  <div id="errorExplanation">
    <h2><%= pluralize(@shoe.errors.count, "error") %></h2>
    <ul>
    <% @shoe.errors.full_messages.each do |msg| -%>
      <li><%= msg %></li>
    <% end -%>
    </ul>
  </div>
  <% end -%>
  
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :size %>
    <%= f.select :size, %w[6 7 8 9 10 11 12 13+] %>
  </p>

  <p>
    <%= f.label :color %>
    <%= f.select :color, %w[white black white/black gray blue/red] %>
  </p>

  <p>
    <div><%= f.label :description %></div>
    <%= f.text_area :description %>
  </p>

  <%= f.submit %>
  <% if @shoe.new_record? -%>
    <%= link_to "Cancel", shoes_path %>
  <% else -%>
    <%= link_to "Cancel", @shoe %>
  <% end -%>
<% end -%>

http/frameworks/rails-example/app/views/shoes/edit.erb
<h1>Edit Shoe</h1>
<%= render :partial => "form" %>

http/frameworks/rails-example/app/views/shoes/index.erb
<h1>Shoes</h1>
<dl>
<% @shoes.each do |shoe| -%>
  <dt><%= shoe.name %></dt>
  <dd>Color: <%= shoe.color %></dd>
  <dd>Size: <%= shoe.size %></dd>
  <dd><%= shoe.description %></dd>
  <dd>
    <%= link_to "Show", shoe %> /
    <%= link_to "Edit", edit_shoe_path(shoe) %> /
    <%= link_to "Remove", shoe, :method => :delete %>
  </dd>
<% end -%>
</dl>

<%= link_to "Add a shoe", new_shoe_path %>

http/frameworks/rails-example/app/views/shoes/new.erb
<h1>Add a Shoe</h1>
<%= render :partial => "form" %>

http/frameworks/rails-example/app/views/shoes/show.erb
<%= link_to "All Shoes", shoes_path %>

<h1><%= @shoe.name %></h1>

<div>Color: <%= @shoe.color %></div>

<div>Size: <%= @shoe.size %></div>

<p><%= @shoe.description %></p>

<div>
  <%= link_to "Edit", edit_shoe_path(@shoe) %> /
  <%= link_to "Remove", @shoe, :method => :delete %>
</div>