http/frameworks/cup/config/routes.rb
Cup::Application.routes.draw do
  resources :drinks

end

http/frameworks/cup/app/models/drink.rb
class Drink < ActiveRecord::Base
  validates :amount, :inclusion => { :in => 0...10 }
end

http/frameworks/cup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

http/frameworks/cup/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @drinks = Drink.all
  end

  def new
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(params[:drink])
    if @drink.save
      redirect_to drinks_path
    else
      render :action => "new"
    end
  end
end

http/frameworks/cup/app/helpers/application_helper.rb
module ApplicationHelper
end

http/frameworks/cup/app/views/drinks/index.erb
<h1>Drinks</h1>

<ul>
<% @drinks.each do |drink| -%>
  <li><%= drink.amount %></li>
<% end -%>
</ul>

<%= link_to "Take a drink", new_drink_path %>

http/frameworks/cup/app/views/drinks/new.erb
<%= form_for @drink do |f| %>
  <% if @drink.errors.any? -%>
  <div id="errorExplanation">
    <h2><%= pluralize(@drink.errors.count, "error") %></h2>
    <ul>
    <% @drink.errors.full_messages.each do |msg| -%>
      <li><%= msg %></li>
    <% end -%>
    </ul>
  </div>
  <% end -%>
  
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <%= f.submit %>
<% end -%>

http/frameworks/cup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cup</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>